saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r"^$", views.product_list, name="product-list"),
    url(r"^(?P<pk>[0-9]+)/$", views.product_details, name="product-details"),
    url(
        r"^(?P<pk>[0-9]+)/publish/$",
        views.product_toggle_is_published,
        name="product-publish",
    ),
    url(
        r"^add/select-type/$", views.product_select_type, name="product-add-select-type"
    ),
    url(r"^add/(?P<type_pk>[0-9]+)/$", views.product_create, name="product-add"),
    url(r"^(?P<pk>[0-9]+)/update/$", views.product_edit, name="product-update"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.product_delete, name="product-delete"),
    url(r"^bulk-update/$", views.product_bulk_update, name="product-bulk-update"),
    url(r"^ajax/products/$", views.ajax_products_list, name="ajax-products"),
    url(r"^types/$", views.product_type_list, name="product-type-list"),
    url(r"^types/add/$", views.product_type_create, name="product-type-add"),
    url(
        r"^types/(?P<pk>[0-9]+)/update/$",
        views.product_type_edit,
        name="product-type-update",
    ),
    url(
        r"^types/(?P<pk>[0-9]+)/delete/$",
        views.product_type_delete,
        name="product-type-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$",
        views.variant_details,
        name="variant-details",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/add/$",
        views.variant_create,
        name="variant-add",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$",
        views.variant_edit,
        name="variant-update",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$",
        views.variant_delete,
        name="variant-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$",
        views.variant_images,
        name="variant-images",
    ),
    url(
        r"^ajax/variants/$",
        views.ajax_available_variants_list,
        name="ajax-available-variants",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/$",
        views.product_images,
        name="product-image-list",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/add/$",
        views.product_image_create,
        name="product-image-add",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$",
        views.product_image_edit,
        name="product-image-update",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$",
        views.product_image_delete,
        name="product-image-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/reorder/$",
        views.ajax_reorder_product_images,
        name="product-images-reorder",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/upload/$",
        views.ajax_upload_image,
        name="product-images-upload",
    ),
    url(r"attributes/$", views.attribute_list, name="attributes"),
    url(
        r"attributes/(?P<pk>[0-9]+)/$",
        views.attribute_details,
        name="attribute-details",
    ),
    url(r"attributes/add/$", views.attribute_create, name="attribute-add"),
    url(
        r"attributes/(?P<pk>[0-9]+)/update/$",
        views.attribute_edit,
        name="attribute-update",
    ),
    url(
        r"attributes/(?P<pk>[0-9]+)/delete/$",
        views.attribute_delete,
        name="attribute-delete",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/add/$",
        views.attribute_value_create,
        name="attribute-value-add",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$",  # noqa
        views.attribute_value_edit,
        name="attribute-value-update",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$",  # noqa
        views.attribute_value_delete,
        name="attribute-value-delete",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/values/reorder/$",
        views.ajax_reorder_attribute_values,
        name="attribute-values-reorder",
    ),

    #  Custom clippath object
    #  url(r'^(?P<product_pk>[0-9]+)/clippath/$',
    #      views.product_clippath, name='product-clippath-list'),
    url(r'^(?P<product_pk>[0-9]+)/clippath/add/$',
        views.product_clippath_create, name='product-clippath-add'),
    url(r'^(?P<product_pk>[0-9]+)/clippath/(?P<clippath_pk>[0-9]+)/$',
        views.product_clippath_edit, name='product-clippath-update'),
    url(r'^(?P<product_pk>[0-9]+)/clippath/(?P<clippath_pk>[0-9]+)/delete/$',
        views.product_clippath_delete, name='product-clippath-delete'),
    url(r'^(?P<product_pk>[0-9]+)/clippath/reorder/$',
        views.ajax_reorder_product_clippath, name='product-clippath-reorder'),
    url(r'^(?P<product_pk>[0-9]+)/clippath/upload/$',
        views.ajax_upload_clippath, name='product-clippath-upload'),
]

saleor/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"^(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/$",
        views.product_details,
        name="details",
    ),
    url(
        r"^digital-download/(?P<token>[0-9A-Za-z_\-]+)/$",
        views.digital_product,
        name="digital-product",
    ),
    url(
        r"^category/(?P<slug>[a-z0-9-_]+?)-(?P<category_id>[0-9]+)/$",
        views.category_index,
        name="category",
    ),
    url(
        r"(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/add/$",
        views.product_add_to_checkout,
        name="add-to-checkout",
    ),
    url(
        r"^collection/(?P<slug>[a-z0-9-_/]+?)-(?P<pk>[0-9]+)/$",
        views.collection_index,
        name="collection",
    ),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^dashboard/", include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r"^__debug__/", include(debug_toolbar.urls)),
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve),
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

saleor/product/forms.py
import json

from django import forms
from django.utils.encoding import smart_text
from django.utils.translation import pgettext_lazy
from django_prices.templatetags.prices_i18n import amount

from ..checkout.forms import AddToCheckoutForm
from ..core.utils.taxes import display_gross_prices


class VariantChoiceField(forms.ModelChoiceField):
    discounts = None
    taxes = None
    display_gross = True

    def label_from_instance(self, obj):
        variant_label = smart_text(obj)
        price = obj.get_price(self.discounts, self.taxes)
        price = price.gross if self.display_gross else price.net
        label = pgettext_lazy(
            "Variant choice field label", "%(variant_label)s - %(price)s"
        ) % {"variant_label": variant_label, "price": amount(price)}
        return label

    def update_field_data(self, variants, discounts, taxes):
        """Initialize variant picker metadata."""
        self.queryset = variants
        self.discounts = discounts
        self.taxes = taxes
        self.empty_label = None
        self.display_gross = display_gross_prices()
        images_map = {
            variant.pk: [vi.image.image.url for vi in variant.variant_images.all()]
            for variant in variants.all()
        }
        self.widget.attrs["data-images"] = json.dumps(images_map)
        # Don't display select input if there is only one variant.
        if self.queryset.count() == 1:
            self.widget = forms.HiddenInput({"value": variants.all()[0].pk})


class ProductForm(AddToCheckoutForm):
    variant = VariantChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        variant_field = self.fields["variant"]
        variant_field.update_field_data(
            self.product.variants.all(), self.discounts, self.taxes
        )

    def get_variant(self, cleaned_data):
        return cleaned_data.get("variant")

saleor/product/views.py
import datetime
import json
import mimetypes
import os
from typing import Union

from django.http import (
    FileResponse,
    HttpResponseNotFound,
    HttpResponsePermanentRedirect,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.core import serializers

from ..checkout.utils import set_checkout_cookie
from ..core.utils import serialize_decimal
from ..seo.schema.product import product_json_ld
from .filters import ProductCategoryFilter, ProductCollectionFilter
from .models import Category, DigitalContentUrl
from .utils import (
    collections_visible_to_user,
    get_product_images,
    get_product_list_context,
    handle_checkout_form,
    products_for_checkout,
    products_for_products_list,
    products_with_details,
)
from .utils.attributes import get_product_attributes_data
from .utils.availability import get_product_availability
from .utils.digital_products import (
    digital_content_url_is_valid,
    increment_download_count,
)
from .utils.variants_picker import get_variant_picker_data
from ..arivarton.models import Font


def product_details(request, slug, product_id, form=None):
    """Product details page.

    The following variables are available to the template:

    product:
        The Product instance itself.

    is_visible:
        Whether the product is visible to regular users (for cases when an
        admin is previewing a product before publishing).

    form:
        The add-to-checkout form.

    price_range:
        The PriceRange for the product including all discounts.

    undiscounted_price_range:
        The PriceRange excluding all discounts.

    discount:
        Either a Price instance equal to the discount value or None if no
        discount was available.

    local_price_range:
        The same PriceRange from price_range represented in user's local
        currency. The value will be None if exchange rate is not available or
        the local currency is the same as site's default currency.
    """
    products = products_with_details(user=request.user)
    product = get_object_or_404(products, id=product_id)
    fonts = serializers.serialize('json', Font.objects.all())
    if product.get_slug() != slug:
        return HttpResponsePermanentRedirect(product.get_absolute_url())
    today = datetime.date.today()
    is_visible = product.publication_date is None or product.publication_date <= today
    if form is None:
        form = handle_checkout_form(request, product, create_checkout=False)[0]
    availability = get_product_availability(
        product,
        discounts=request.discounts,
        taxes=request.taxes,
        local_currency=request.currency,
    )
    product_images = get_product_images(product)
    variant_picker_data = get_variant_picker_data(
        product, request.discounts, request.taxes, request.currency
    )
    product_attributes = get_product_attributes_data(product)
    # show_variant_picker determines if variant picker is used or select input
    show_variant_picker = all([v.attributes for v in product.variants.all()])
    json_ld_data = product_json_ld(product, product_attributes)
    ctx = {
        'fonts': fonts,
        "is_visible": is_visible,
        "form": form,
        "availability": availability,
        "product": product,
        "product_attributes": product_attributes,
        "product_images": product_images,
        "show_variant_picker": show_variant_picker,
        "variant_picker_data": json.dumps(
            variant_picker_data, default=serialize_decimal
        ),
        "json_ld_product_data": json.dumps(json_ld_data, default=serialize_decimal),
    }
    return TemplateResponse(request, "product/details.html", ctx)


def digital_product(request, token: str) -> Union[FileResponse, HttpResponseNotFound]:
    """Returns direct download link to content if given token is still valid"""

    qs = DigitalContentUrl.objects.prefetch_related("line__order__user")
    content_url = get_object_or_404(qs, token=token)  # type: DigitalContentUrl
    if not digital_content_url_is_valid(content_url):
        return HttpResponseNotFound("Url is not valid anymore")

    digital_content = content_url.content
    digital_content.content_file.open()
    opened_file = digital_content.content_file.file
    filename = os.path.basename(digital_content.content_file.name)
    file_expr = 'filename="{}"'.format(filename)

    content_type = mimetypes.guess_type(str(filename))[0]
    response = FileResponse(opened_file)
    response["Content-Length"] = digital_content.content_file.size

    response["Content-Type"] = content_type
    response["Content-Disposition"] = "attachment; {}".format(file_expr)

    increment_download_count(content_url)
    return response


def product_add_to_checkout(request, slug, product_id):
    # types: (int, str, dict) -> None

    if not request.method == "POST":
        return redirect(
            reverse("product:details", kwargs={"product_id": product_id, "slug": slug})
        )

    products = products_for_checkout(user=request.user)
    product = get_object_or_404(products, pk=product_id)
    form, checkout = handle_checkout_form(request, product, create_checkout=True)
    if form.is_valid():
        form.save()
        if request.is_ajax():
            response = JsonResponse({"next": reverse("checkout:index")}, status=200)
        else:
            response = redirect("checkout:index")
    else:
        if request.is_ajax():
            response = JsonResponse({"error": form.errors}, status=400)
        else:
            response = product_details(request, slug, product_id, form)
    if not request.user.is_authenticated:
        set_checkout_cookie(checkout, response)
    return response


def category_index(request, slug, category_id):
    categories = Category.objects.prefetch_related("translations")
    category = get_object_or_404(categories, id=category_id)
    if slug != category.slug:
        return redirect(
            "product:category",
            permanent=True,
            slug=category.slug,
            category_id=category_id,
        )
    # Check for subcategories
    categories = category.get_descendants(include_self=True)
    products = (
        products_for_products_list(user=request.user)
        .filter(category__in=categories)
        .order_by("name")
        .prefetch_related("collections")
    )
    product_filter = ProductCategoryFilter(
        request.GET, queryset=products, category=category
    )
    ctx = get_product_list_context(request, product_filter)
    ctx.update({"object": category})
    return TemplateResponse(request, "category/index.html", ctx)


def collection_index(request, slug, pk):
    collections = collections_visible_to_user(request.user).prefetch_related(
        "translations"
    )
    collection = get_object_or_404(collections, id=pk)
    if collection.slug != slug:
        return HttpResponsePermanentRedirect(collection.get_absolute_url())
    products = (
        products_for_products_list(user=request.user)
        .filter(collections__id=collection.id)
        .order_by("name")
    )
    product_filter = ProductCollectionFilter(
        request.GET, queryset=products, collection=collection
    )
    ctx = get_product_list_context(request, product_filter)
    ctx.update({"object": collection})
    return TemplateResponse(request, "collection/index.html", ctx)

umg/reverse/templates/product/details.html
{% extends "base.html" %}

{% load bootstrap_field from bootstrap4 %}
{% load build_absolute_uri from urls %}
{% load get_object_properties from attributes %}
{% load get_thumbnail from product_images %}
{% load get_product_image_thumbnail from product_images %}
{% load i18n %}
{% load markdown from markdown %}
{% load placeholder %}
{% load static %}
{% load taxed_prices %}
{% load fonts %}

{% block title %}
  {% if product.seo_title %}
    {{ product.translated.seo_title }}
  {% else %}
    {{ product.translated.name }} - {{ block.super }}
  {% endif %}
{% endblock %}

{% block stylesheet %}
  {{ block.super }}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
{% endblock stylesheet %}

{% block meta_tags %}
  <meta property="og:title" content="{{ product.translated.seo_title|default:product.translated.name }}">
  <meta property="og:description" content="{{ product.translated.seo_description|default:"" }}">
  <meta name="description" content="{{ product.translated.seo_description|default:"" }}">

  {% build_absolute_uri request=request location=product.get_absolute_url as product_url %}
  <meta property="og:url" content="{{ product_url }}">
  <link rel="canonical" href="{{ product_url }}">
  <link href="{% get_fonts_url %}" rel="stylesheet">

  {% get_product_image_thumbnail product.get_first_image size=510 method="thumbnail" as product_image %}
  {% if product_image %}
    <meta property="og:image" content="{{ product_image }}" />
    <meta property="og:image:width" content="510">
    <meta property="og:image:height" content="510">
  {% else %}
    <meta property="og:image" content="{% static "images/block1.png" %}">
  {% endif %}
{% endblock meta_tags %}

{% block breadcrumb %}
  <ul class="breadcrumbs list-unstyled">
    <li>
      <a href="{% url 'home' %}">
        {% trans "Home" context "Main navigation item" %}
      </a>
    </li>
    {% if product.category %}
      <li>
        <a href="{{ product.category.get_absolute_url }}">{{ product.category.translated }}</a>
      </li>
    {% endif %}
    <li>
      <a href="{{ product.get_absolute_url }}">{{ product.translated }}</a>
    </li>
  </ul>
{% endblock breadcrumb %}

{% block content %}
  {% if not is_visible %}
    <div class="alert alert-warning" role="alert">
      {% blocktrans trimmed with date=product.publication_date|date context "Product details text" %}
        <strong>Warning!</strong>
        You are previewing a product that will become visible on <strong>{{ date }}</strong>.
      {% endblocktrans %}
    </div>
  {% endif %}
  <div class="row product__customizer" style="display: none;">
    <div class="col-md-12">
        <h2 id="canvas-front-header">{% trans "Front" %}</h2>
        <h2 id="canvas-back-header" style="display: none;">{% trans "Back" %}</h2>
        <div class="product__customizer__wrapper">
            <div id="product__customizer__nav">
                <div class="row">
                <div class="col-6">
                    <button id="add-image" data-toggle="modal" data-target="#ImageUploadModal"><i class="fas fa-image"></i></button>
                    <!-- Modal for uploading images -->
                    <div class="modal fade" id="ImageUploadModal" tabindex="-1" role="dialog" aria-labelledby="ImageUploadModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                              <h5 class="modal-title" id="ImageUploadModalLabel">{% trans "Image upload" %}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                              <input type="file" id="ImageUploadInput"></input>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Close" %}</button>
                            <button type="button" class="btn btn-primary">{% trans "Upload" %}</button>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- End of: Modal for uploading images -->
                    <button id="add-text"><i class="fas fa-font"></i></button>
                    <button id="show-layers" data-toggle="modal" data-target="#LayerListModal"><i class="fas fa-th-list"></i></button>
                    <!-- Modal for layer list -->
                    <div class="modal fade" id="LayerListModal" tabindex="-1" role="dialog" aria-labelledby="LayerListModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                              <h5 class="modal-title" id="LayerListModalLabel">{% trans "Layer list" %}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                              <ul id="layers">
                              </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- End of: Modal for layer list -->
                  </ul>
                </div>
                <div class="col-6">
                  <ul class="float-right">
                    <button id="rotate-canvas"><i class="fas fa-sync-alt"></i></button>
                    <button id="save-canvas"><i class="fas fa-save"></i></button>
                </div>
                </div>
            </div>
            {% if product.is_glass %}
            <div id="canvas-wrapper" canvas-max-size="1110" canvas_image="{{ product.clippath.image.url }}">
                <canvas id="canvas-front"></canvas>
                <canvas id="canvas-back" style="display: none;"></canvas>
            </div>
            {% elif product.is_sign %}
            {% endif %}
        </div>
    </div>
  </div>

  <div class="row product">
    <script type="application/ld+json">{{ json_ld_product_data|safe }}</script>
    <div class="col-md-6 col-12 product__gallery">
      {% with images=product_images %}
        {% if images %}
          <div id="carousel-example-generic" class="carousel slide">
            <div class="carousel-inner" role="listbox">
              {% for image in images %}
                <div class="carousel-item{% if forloop.first %} active{% endif %}">
                  <div class="product-image">
                    <img class="d-block img-fluid lazyload lazypreload"
                         data-src="{% get_thumbnail image.image method="thumbnail" size=540 %}"
                         data-srcset="{% get_thumbnail image.image method="thumbnail" size=540 %} 1x, {% get_thumbnail image.image method="thumbnail" size=1110 %} 2x"
                         alt=""
                         src="{% placeholder size=540 %}">
                  </div>
                </div>
              {% endfor %}
            </div>
            {% if images|length > 1 %}
              <a class="carousel-control-prev" href="#carousel-example-generic" role="button" data-slide="prev">
                <svg data-src="{% static "images/gallery-arrow.svg" %}" />
              </a>
              <a class="carousel-control-next" href="#carousel-example-generic" role="button" data-slide="next">
                <svg data-src="{% static "images/gallery-arrow.svg" %}" />
              </a>
            {% endif %}
            <ol class="carousel-indicators d-none d-md-block">
              {% for image in images %}
                {% if images|length > 1 %}
                  <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}"{% if forloop.first %} class="active"{% endif %}>
                    <img data-src="{% get_thumbnail image.image method="thumbnail" size=60 %}"
                         data-srcset="{% get_thumbnail image.image method="thumbnail" size=60 %} 1x, {% get_thumbnail image.image method="thumbnail" size=120 %} 2x"
                         alt=""
                         class="lazyload lazypreload"
                         src="{% placeholder size=60 %}">
                  </li>
                {% endif %}
              {% endfor %}
            </ol>
          </div>
        {% else %}
          <img data-src="{% placeholder size=540 %}"
               data-srcset="{% placeholder size=540 %} 1x, {% placeholder size=1080 %} 2x"
               alt=""
               class="img-fluid lazyload lazypreload">
        {% endif %}
      {% endwith %}
    </div>
    <div class="col-md-6 col-12 product__info">
      <h1 class="product__info__name">
        {{ product.translated }}
      </h1>
      <p>
      {% if product.clippath %}
        <a href="#" id="customize-product-link">
          {% trans "Customize product" %}
        </a>
      {% else %}
        {% trans "Not customizable" %}
      {% endif %}
      </p>
      {% if user.is_staff %}
        <p>
          <a href="{% url "dashboard:product-details" pk=product.pk %}">
            {% trans "Edit in dashboard" context "Product details link text" %}
          </a>
        </p>
      {% endif %}
      {% if availability.available %}
        {% if show_variant_picker %}
          <div id="variant-price-component"></div>
        {% else %}
          <h2 class="product__info__price">
            <span>{% price_range availability.price_range %}</span>
            {% if availability.on_sale %}
              <small class="product__info__price__undiscounted">
                {% price availability.price_range_undiscounted %}
              </small>
            {% endif %}
            {% if availability.price_range_local_currency %}
              <br>
              <small class="text-info">
                &asymp;
                {% price availability.price_range_local_currency %}
              </small>
            {% endif %}
            {% if request.taxes %}
              <small>
                {% tax_rate request.taxes product.tax_rate as tax_rate %}
                {% if site.settings.display_gross_prices %}
                  {% blocktrans trimmed with tax_rate=tax_rate context "Product details page vat rate value" %}
                    including {{ tax_rate }}% VAT
                  {% endblocktrans %}
                {% else %}
                  {% blocktrans trimmed with tax_rate=tax_rate context "Product details page vat rate value" %}
                    excluding {{ tax_rate }}% VAT
                  {% endblocktrans %}
                {% endif %}
              </small>
            {% endif %}
          </h2>
        {% endif %}
      {% endif %}
      {% if is_visible and product.is_in_stock %}
        {% block orderform %}
          {% if show_variant_picker %}
            {% csrf_token %}
            <div id="variant-picker" data-variant-picker-data="{{ variant_picker_data }}" data-action="{% url 'product:add-to-checkout' product_id=product.pk slug=product.get_slug %}"></div>
          {% else %}
            <form id="product-form" role="form" class="product-form clearfix" method="post" action="{% url 'product:add-to-checkout' product_id=product.pk slug=product.get_slug %}" novalidate>
              {% csrf_token %}
              {% bootstrap_field form.variant %}
              <div class="product__info__quantity">
                {% bootstrap_field form.quantity %}
              </div>

              <div class="form-group product__info__button">
                <button class="btn btn-primary">
                  {% trans "Add to cart" context "Product details primary action" %}
                </button>
              </div>
            </form>
          {% endif %}
        {% endblock %}
        <div class="product__info__form-error">
          <small class="text-danger"></small>
        </div>

      {% else %}
        <p class="alert alert-warning">
          {% blocktrans context "Product details text" %}This product is currently <strong>unavailable</strong>.{% endblocktrans %}
        </p>
      {% endif %}
      <div class="product__info__description">
        <h3>{% trans "Description" context "Product details title" %}</h3>
        <hr>
        {{ product.translated.description|safe }}
      </div>
      <table>
        {% for attribute, value in product_attributes.items %}
          <tr>
            <td>{{ attribute.translated }}:</td>
            <td><strong>{{ value.translated }}</strong></td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
  <script type="text/javascript">
      fonts_from_django = {{ fonts|safe }};
  </script>
{% endblock content %}