saleor/dashboard/arivarton/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # Product customization
    # Fonts
    url(r'^$',
        views.font_list, name='font-list'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.font_details, name='font-details'),
    url(r'^add/$',
        views.font_create, name='font-add'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.font_edit, name='font-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.font_delete, name='font-delete'),
    url(r'^bulk-update/$',
        views.font_bulk_update, name='font-bulk-update')
    ]

saleor/dashboard/menu/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.menu_list, name="menu-list"),
    url(r"^add/$", views.menu_create, name="menu-add"),
    url(r"^(?P<pk>[0-9]+)/edit/$", views.menu_edit, name="menu-edit"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.menu_delete, name="menu-delete"),
    url(r"^(?P<pk>[0-9]+)/$", views.menu_details, name="menu-details"),
    url(r"^(?P<menu_pk>[0-9]+)/add/$", views.menu_item_create, name="menu-item-add"),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/add/$",
        views.menu_item_create,
        name="menu-item-add",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/edit/$",
        views.menu_item_edit,
        name="menu-item-edit",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/delete/$",
        views.menu_item_delete,
        name="menu-item-delete",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/$",
        views.menu_item_details,
        name="menu-item-details",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(r"^ajax/links/$", views.ajax_menu_links, name="ajax-menu-links"),
]

saleor/dashboard/page/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.page_list, name="page-list"),
    url(r"^add/$", views.page_add, name="page-add"),
    url(r"^(?P<pk>[0-9]+)/$", views.page_details, name="page-details"),
    url(r"^(?P<pk>[0-9]+)/update/$", views.page_update, name="page-update"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.page_delete, name="page-delete"),
]

saleor/dashboard/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .collection.urls import urlpatterns as collection_urls
from .customer.urls import urlpatterns as customer_urls
from .discount.urls import urlpatterns as discount_urls
from .menu.urls import urlpatterns as menu_urls
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls
from .sites.urls import urlpatterns as site_urls
from .staff.urls import urlpatterns as staff_urls
from .taxes.urls import urlpatterns as taxes_urls

from .arivarton.urls import urlpatterns as arivarton_urls

urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^collections/', include(collection_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^page/', include(page_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^staff/', include(staff_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^settings/', include(site_urls)),
    url(r'^menu/', include(menu_urls)),
    url(r'^shipping/', include(shipping_urls)),
    url(r'^style-guide/', core_views.styleguide, name='styleguide'),
    url(r'^search/', include(search_urls)),
    url(r'^taxes/', include(taxes_urls)),
    url(r'^next/', TemplateView.as_view(template_name='dashboard/next.html')),
    url(r'^product_customization/', include(arivarton_urls)),
    ]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^dashboard/", include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r"^__debug__/", include(debug_toolbar.urls)),
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve),
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

saleor/dashboard/arivarton/forms.py
from django import forms
from django.utils.translation import pgettext_lazy

from ...arivarton.models import Font

class FontForm(forms.ModelForm):
    name = forms.CharField(
        required=True,
        label=pgettext_lazy('Font name in google fonts', 'Font name'))

    class Meta:
        model = Font
        exclude = []
        labels = {
            'name': pgettext_lazy('Item name', 'Name')}

saleor/dashboard/category/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.utils.translation import pgettext_lazy
from text_unidecode import unidecode

from ...product.models import Category
from ...product.thumbnails import create_category_background_image_thumbnails
from ..seo.fields import SeoDescriptionField, SeoTitleField


class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.parent_pk = kwargs.pop("parent_pk")
        super().__init__(*args, **kwargs)
        self.fields["seo_description"] = SeoDescriptionField(
            extra_attrs={"data-bind": self["description"].auto_id}
        )
        self.fields["seo_title"] = SeoTitleField(
            extra_attrs={"data-bind": self["name"].auto_id}
        )

    class Meta:
        model = Category
        exclude = ["slug", "description_json"]
        labels = {
            "name": pgettext_lazy("Item name", "Name"),
            "description": pgettext_lazy("Description", "Description"),
            "background_image": pgettext_lazy("Category form", "Background Image"),
            "background_image_alt": pgettext_lazy(
                "Description of a category image", "Image description"
            ),
        }

    def save(self, commit=True):
        self.instance.slug = slugify(unidecode(self.instance.name))

        if self.parent_pk:
            self.instance.parent = get_object_or_404(Category, pk=self.parent_pk)

        instance = super().save(commit=commit)

        if instance.pk and "background_image" in self.changed_data:
            create_category_background_image_thumbnails.delay(instance.pk)

        return instance

saleor/dashboard/arivarton/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy, npgettext_lazy
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_POST

from . import forms
from ..views import staff_member_required
from ...arivarton.models import Font

@staff_member_required
@permission_required(['site.manage_settings', 'page.manage_pages'])
def font_list(request):
    fonts = Font.objects.all().order_by('name')
    ctx = {
        'fonts': fonts
    }
    return TemplateResponse(request, 'dashboard/fonts/list.html', ctx)


def font_details(request, pk):
    font = get_object_or_404(Font, pk=pk)

    ctx = {
        'font': font}
    return TemplateResponse(request, 'dashboard/fonts/detail.html', ctx)


@staff_member_required
@permission_required(['site.manage_settings', 'page.manage_pages'])
def font_create(request):
    font = Font()
    font_form = forms.FontForm(request.POST or None, instance=font)
    if font_form.is_valid():
        font.name = font.get_font_info()['family']
        font = font_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added font %s') % (font,)
        messages.success(request, msg)
        return redirect('dashboard:font-list')
    ctx = {
        'font_form': font_form,
        'font': font}
    return TemplateResponse(request, 'dashboard/fonts/form.html', ctx)


@staff_member_required
@permission_required(['site.manage_settings', 'page.manage_pages'])
def font_edit(request, pk):
    font = get_object_or_404(Font, pk=pk)
    form = forms.FontForm(request.POST or None, instance=font)

    if form.is_valid():
        font = form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Updated font %s') % (font,)
        messages.success(request, msg)
        return redirect('dashboard:font-details', pk=font.pk)
    ctx = {
        'font': font, 'font_form': form}
    return TemplateResponse(request, 'dashboard/fonts/form.html', ctx)


@staff_member_required
@permission_required(['site.manage_settings', 'page.manage_pages'])
def font_delete(request, pk):
    font = get_object_or_404(Font, pk=pk)
    if request.method == 'POST':
        font.delete()
        msg = pgettext_lazy(
            'Dashboard message', 'Removed font %s') % (font,)
        messages.success(request, msg)
        return redirect('dashboard:font-list')
    return TemplateResponse(
        request,
        'dashboard/fonts/modal/confirm_delete.html',
        {'font': font})


@require_POST
@staff_member_required
@permission_required(['site.manage_settings', 'page.manage_pages'])
def font_bulk_update(request):
    form = forms.FontBulkUpdate(request.POST)
    if form.is_valid():
        form.save()
        count = len(form.cleaned_data['fonts'])
        msg = npgettext_lazy(
            'Dashboard message',
            '%(count)d font has been updated',
            '%(count)d fonts have been updated',
            number='count') % {'count': count}
        messages.success(request, msg)
    return redirect('dashboard:font-list')

saleor/dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Category
from ..menu.utils import get_menus_that_needs_update, update_menus
from ..views import staff_member_required
from .filters import CategoryFilter
from .forms import CategoryForm


@staff_member_required
@permission_required("product.manage_products")
def category_list(request):
    categories = Category.tree.root_nodes().order_by("name")
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "categories": categories,
        "filter_set": category_filter,
        "is_empty": not category_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/category/list.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, request.FILES or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request, pgettext_lazy("Dashboard message", "Added category %s") % category
        )
        if root_pk:
            return redirect("dashboard:category-details", pk=root_pk)
        return redirect("dashboard:category-list")
    ctx = {"category": category, "form": form, "path": path}
    return TemplateResponse(request, "dashboard/category/form.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(
        request.POST or None,
        request.FILES or None,
        instance=category,
        parent_pk=category.parent_id,
    )
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy("Dashboard message", "Updated category %s") % category,
        )
        if root_pk:
            return redirect("dashboard:category-details", pk=root_pk)
        return redirect("dashboard:category-list")
    elif form.errors:
        status = 400
    ctx = {"category": category, "form": form, "status": status, "path": path}
    template = "dashboard/category/form.html"
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required("product.manage_products")
def category_details(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by("name")
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "categories": categories,
        "path": path,
        "root": root,
        "filter_set": category_filter,
        "is_empty": not category_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/category/detail.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        descendants = category.get_descendants()
        menus = get_menus_that_needs_update(categories=descendants)
        category.delete()
        if menus:
            update_menus(menus)
        messages.success(
            request,
            pgettext_lazy("Dashboard message", "Removed category %s") % category,
        )
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {
                    "redirectUrl": reverse(
                        "dashboard:category-details", kwargs={"pk": root_pk}
                    )
                }
                return JsonResponse(response)
            return redirect("dashboard:category-details", pk=root_pk)
        else:
            if request.is_ajax():
                response = {"redirectUrl": reverse("dashboard:category-list")}
                return JsonResponse(response)
            return redirect("dashboard:category-list")
    ctx = {
        "category": category,
        "descendants": list(category.get_descendants()),
        "products_count": len(category.products.all()),
    }
    return TemplateResponse(
        request, "dashboard/category/modal/confirm_delete.html", ctx
    )

umg/reverse/templates/dashboard/fonts/detail.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load price from taxed_prices %}
{% load static %}
{% load status %}
{% load utils %}

{% block title %}{{ font }} - {{ block.super }}{% endblock %}

{% block body_class %}body-fonts{% endblock %}

{% block menu_fonts_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:font-list" %}" class="breadcrumb">
        {% trans "Fonts" context "Font form breadcrumbs" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:font-list" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {{ font }}
      </span>
    </li>
  </ul>
{% endblock %}
{% block content %}
  <div class="row">
    <div class="col s12 l8">
      <div class="card">
        <div class="card-content">
          <div class="font-header">
            <div class="font-header__title">
              <span class="card-title">
                <a href="{{ font.get_url }}">{{ font }}</a>
              </span>
            </div>
            <div class="font-header__switch">
            </div>
          </div>
        </div>
        <div class="card-action">
          <a href="{% url "dashboard:font-update" font.pk %}" class="btn-flat waves-effect">
            {% trans "Edit font" context "Font action" %}
          </a>
          <a href="#base-modal" data-href="{% url 'dashboard:font-delete' pk=font.pk %}" class="modal-trigger-custom btn-flat waves-effect">
            {% trans "Remove font" context "Font action" %}
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

umg/reverse/templates/dashboard/fonts/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}
  {% if font.pk %}
    {% trans "Edit" context "Dashboard font list" %} - {{ font }}
  {% else %}
    {% trans "Add new font" context "Font form page title" %}
  {% endif %}
   - {{ block.super }}
{% endblock %}

{% block body_class %}body-fonts{% endblock %}

{% block menu_fonts_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:font-list" as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:font-list" %}" class="breadcrumb">
        {% trans "Fonts" context "Dashboard fonts list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:font-list" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      {% if font.pk %}
        <a href="{% url "dashboard:font-details" pk=font.pk %}" class="breadcrumbs--ellipsed-item">
          {{ font }}
        </a>
      {% else %}
        <span class="breadcrumbs--ellipsed-item">
          {% trans "Add new font" context "Font form breadcrumbs" %}
        </span>
      {% endif %}
    </li>
    {% if font.pk %}
      <li>
        <span class="breadcrumbs--ellipsed-item">
          {% trans "Edit" context "Font form breadcrumbs" %}
        </span>
      </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="tab-content" id="details">
    <div class="row">
      <div class="col m12 l9">
        <form method="post" class="card" id="form-font" novalidate>
          {% csrf_token %}
          <div class="card-content">
            <div class="row">
              <div class="col s12 l8" >
                <div class="row">
                  {{ font_form.name|materializecss }}
                </div>
              </div>
            </div>
          </div>
          <div class="card-action right-align">
            {% if font.pk %}
              <a href="{% url 'dashboard:font-details' font.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url 'dashboard:font-list' %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
      <div class="col m12 l3 help-box"></div>
    </div>
  </div>
{% endblock %}

umg/reverse/templates/dashboard/fonts/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load price from taxed_prices %}
{% load static %}
{% load utils %}

{% block title %}
  {% trans "Fonts" context "Dashboard font list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-fonts-list{% endblock %}

{% block menu_fonts_class %}active{% endblock %}

{% block header_extra %}
    <div class="btn-fab-fixed">
        <a class="btn-fab-default waves-effect waves-light modal-trigger" href="{% url 'dashboard:font-add' %}" title="{% trans "Add font" context "Font list add button text" %}">
          <svg data-src="{% static "dashboard/images/add.svg" %}" />
        </a>
    </div>
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
      {% trans "Fonts" context "Dashboard fonts list" %}
    </li>
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9" id="font-list">
    {% if fonts %}
      <div class="card">
        <form method="POST" action="{% url 'dashboard:font-bulk-update' %}" novalidate id="bulk-actions-form">
          {% csrf_token %}
          <input name="action" type="hidden" id="bulk-action" />
          {% include 'dashboard/fonts/../includes/_bulk_actions_bar.html' %}
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table last-right-align">
          <thead>
            <tr>
              <th class="bulk-checkbox">
                <input id="select-all-items" type="checkbox" class="filled-in select-all select-item">
                <label for="select-all-items"></label>
              </th>
              {% trans "Name" context "Fonts list table header" as label %}
              {% sorting_header 'name' label %}
            </tr>
          </thead>
          <tbody>
          {% for font in fonts %}
            <tr class="avatar" data-action-go="{% url 'dashboard:font-details' pk=font.pk %}">
              <td class="bulk-checkbox ignore-link">
                <input id="id_fonts_{{ font.pk }}" type="checkbox" name="fonts" value="{{ font.pk }}" class="filled-in select-item">
                <label for="id_fonts_{{ font.pk }}"></label>
              </td>
              <td>
                {{ font.name }}
              </td>
            </tr>
          {% endfor %}
          </tbody>
          </table>
          </div>
        </form>
      </div>
      {% paginate fonts %}
    {% else %}
      {% if not fonts %}
        {% include 'dashboard/fonts/zero_page.html' %}
      {% else %}
        <div class="col s12">
          <div class="not-found">
            <p class="grey-text">
              {% trans "No fonts found." context "Empty font list message" %}
            </p>
          </div>
        </div>
      {% endif %}
    {% endif %}
    </div>
  </div>
{% endblock %}

umg/reverse/templates/dashboard/fonts/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No fonts found." %}{% endblock %}
{% block content %}
  {% static "dashboard/images/add.svg" as img_path %}
  {% blocktrans %}
    You can create fonts by using the <span class="btn-fab-presentation"><svg data-src="{{ img_path }}" /></span> button.
  {% endblocktrans %}
{% endblock %}